"""Explicit mapping from service API names to use-case-owned handlers."""

from __future__ import annotations

from typing import Any

from commerce_service_allocation import (
    _select_server_for_plan,
    _validate_server_allocation_capacity,
    apply_server_policy,
    configure_plan_allocation,
    configure_server_capacity,
    configure_tier_allocation,
    get_plan,
    plan_availability,
    plans,
)
from commerce_service_core import (
    _assert_no_active_promo,
    _audit,
    _decrypt_access_url,
    _encrypt_access_url,
    _ensure_user,
    _health_threshold,
    _lock_order,
    _metric_bytes,
    _queue_customer_repair_notification,
    _queue_receipt_extraction,
    _queue_staff_notification,
    _receipt_risk_flags,
    _receipt_storage_extension,
    _receipt_storage_path,
    _receipt_timestamp,
    _repair_blocks_access,
    _storage_bucket,
    _storage_is_configured,
    _table_exists,
    initialize,
)
from commerce_service_customer import (
    _usage_snapshot_table_available,
    customer_server_ids,
    prune_usage_snapshots,
    receipt_policy,
    set_receipt_mode,
    user_migrated_usage,
    user_usage,
    user_vpn,
    user_vpn_detail,
    user_vpns,
)
from commerce_service_fleet import (
    _connectivity_adapter,
    _failover_source_record,
    _failover_target_has_fresh_probe,
    _normalize_legacy_access_url,
    _outline_client,
    _record_endpoint_health,
    auto_queue_scale_out,
    configure_route_failover_policy,
    connectivity_snapshot,
    endpoint_health_history,
    observe_route_result,
    process_route_failovers,
    queue_infrastructure_provision,
    register_outline_servers,
    route_failover_decisions,
    server_drain_readiness,
    service_route_snapshot,
    set_server_lifecycle,
)
from commerce_service_inventory import (
    approve_managed_key_repair,
    endpoint_migration_jobs,
    ensure_managed_key_repair_notifications,
    managed_key_repair_jobs,
    migratable_credentials,
    queue_endpoint_migration,
    refresh_server_inventory,
    remote_key_inventory,
    review_remote_key,
)
from commerce_service_orders import (
    cancel_order,
    choose_payment_method,
    create_order,
    create_wallet_topup,
    expire_open_orders,
    list_user_orders,
    open_order_ids_for_user,
    order_detail,
    _order_stage,
    pending_order_for_user,
    receipt_duplicate_status,
    reconcile_duplicate_open_orders,
    release_expired_wallet_reservations,
    replace_open_order,
    submit_payment,
)
from commerce_service_receipts import (
    claim_receipt_extraction_job,
    fail_receipt_extraction_job,
    finish_receipt_diagnostic,
    finish_receipt_extraction,
    get_receipt,
    last_receipt_diagnostic,
    list_pending_receipts,
    receipt_system_snapshot,
    reject_receipt,
    start_receipt_diagnostic,
    submit_receipt,
    verify_receipt,
)
from commerce_service_repairs import (
    _enqueue_managed_key_repair,
    _managed_repair_allow_unknown_usage,
    _managed_repair_cached_usage_is_recent,
    _managed_repair_cached_usage_max_age_seconds,
    _managed_repair_key_name,
    _managed_repair_observation_interval_seconds,
    _managed_repair_required_observations,
    _queue_aggregate_revocation,
    _record_aggregate_usage,
    _record_usage_snapshots,
    _usage_snapshot_interval_seconds,
    _managed_repair_rows,
)
from commerce_service_wallet_approval import approve_order
from commerce_service_wallet_payment import credit_wallet, pay_order_with_wallet
from commerce_service_wallet_read import consistency_report, list_pending_orders, wallet_balance, wallet_history
from commerce_service_wallet_refunds import refund_order, reject_order


SERVICE_IMPLEMENTATIONS: dict[str, Any] = {
    name: implementation
    for name, implementation in {
        "_assert_no_active_promo": _assert_no_active_promo,
        "_audit": _audit,
        "_decrypt_access_url": _decrypt_access_url,
        "_encrypt_access_url": _encrypt_access_url,
        "_ensure_user": _ensure_user,
        "_health_threshold": _health_threshold,
        "_lock_order": _lock_order,
        "_metric_bytes": _metric_bytes,
        "_queue_customer_repair_notification": _queue_customer_repair_notification,
        "_queue_receipt_extraction": _queue_receipt_extraction,
        "_queue_staff_notification": _queue_staff_notification,
        "_receipt_risk_flags": _receipt_risk_flags,
        "_receipt_storage_extension": _receipt_storage_extension,
        "_receipt_storage_path": _receipt_storage_path,
        "_receipt_timestamp": _receipt_timestamp,
        "_repair_blocks_access": _repair_blocks_access,
        "_storage_bucket": _storage_bucket,
        "_storage_is_configured": _storage_is_configured,
        "_table_exists": _table_exists,
        "_usage_snapshot_table_available": _usage_snapshot_table_available,
        "customer_server_ids": customer_server_ids,
        "initialize": initialize,
        "prune_usage_snapshots": prune_usage_snapshots,
        "receipt_policy": receipt_policy,
        "set_receipt_mode": set_receipt_mode,
        "user_migrated_usage": user_migrated_usage,
        "user_usage": user_usage,
        "user_vpn": user_vpn,
        "user_vpn_detail": user_vpn_detail,
        "user_vpns": user_vpns,
        "_connectivity_adapter": _connectivity_adapter,
        "_failover_source_record": _failover_source_record,
        "_failover_target_has_fresh_probe": _failover_target_has_fresh_probe,
        "_normalize_legacy_access_url": _normalize_legacy_access_url,
        "_outline_client": _outline_client,
        "_record_endpoint_health": _record_endpoint_health,
        "auto_queue_scale_out": auto_queue_scale_out,
        "configure_route_failover_policy": configure_route_failover_policy,
        "connectivity_snapshot": connectivity_snapshot,
        "endpoint_health_history": endpoint_health_history,
        "observe_route_result": observe_route_result,
        "process_route_failovers": process_route_failovers,
        "queue_infrastructure_provision": queue_infrastructure_provision,
        "register_outline_servers": register_outline_servers,
        "route_failover_decisions": route_failover_decisions,
        "server_drain_readiness": server_drain_readiness,
        "service_route_snapshot": service_route_snapshot,
        "set_server_lifecycle": set_server_lifecycle,
        "approve_managed_key_repair": approve_managed_key_repair,
        "endpoint_migration_jobs": endpoint_migration_jobs,
        "ensure_managed_key_repair_notifications": ensure_managed_key_repair_notifications,
        "managed_key_repair_jobs": managed_key_repair_jobs,
        "migratable_credentials": migratable_credentials,
        "queue_endpoint_migration": queue_endpoint_migration,
        "refresh_server_inventory": refresh_server_inventory,
        "remote_key_inventory": remote_key_inventory,
        "review_remote_key": review_remote_key,
        "create_wallet_topup": create_wallet_topup,
        "create_order": create_order,
        "replace_open_order": replace_open_order,
        "cancel_order": cancel_order,
        "expire_open_orders": expire_open_orders,
        "release_expired_wallet_reservations": release_expired_wallet_reservations,
        "list_user_orders": list_user_orders,
        "reconcile_duplicate_open_orders": reconcile_duplicate_open_orders,
        "order_detail": order_detail,
        "_order_stage": _order_stage,
        "choose_payment_method": choose_payment_method,
        "submit_payment": submit_payment,
        "pending_order_for_user": pending_order_for_user,
        "open_order_ids_for_user": open_order_ids_for_user,
        "receipt_duplicate_status": receipt_duplicate_status,
        "submit_receipt": submit_receipt,
        "claim_receipt_extraction_job": claim_receipt_extraction_job,
        "finish_receipt_extraction": finish_receipt_extraction,
        "fail_receipt_extraction_job": fail_receipt_extraction_job,
        "list_pending_receipts": list_pending_receipts,
        "get_receipt": get_receipt,
        "verify_receipt": verify_receipt,
        "reject_receipt": reject_receipt,
        "start_receipt_diagnostic": start_receipt_diagnostic,
        "finish_receipt_diagnostic": finish_receipt_diagnostic,
        "last_receipt_diagnostic": last_receipt_diagnostic,
        "receipt_system_snapshot": receipt_system_snapshot,
        "_enqueue_managed_key_repair": _enqueue_managed_key_repair,
        "_managed_repair_allow_unknown_usage": _managed_repair_allow_unknown_usage,
        "_managed_repair_cached_usage_is_recent": _managed_repair_cached_usage_is_recent,
        "_managed_repair_cached_usage_max_age_seconds": _managed_repair_cached_usage_max_age_seconds,
        "_managed_repair_key_name": _managed_repair_key_name,
        "_managed_repair_observation_interval_seconds": _managed_repair_observation_interval_seconds,
        "_managed_repair_required_observations": _managed_repair_required_observations,
        "_queue_aggregate_revocation": _queue_aggregate_revocation,
        "_record_aggregate_usage": _record_aggregate_usage,
        "_record_usage_snapshots": _record_usage_snapshots,
        "_usage_snapshot_interval_seconds": _usage_snapshot_interval_seconds,
        "_managed_repair_rows": _managed_repair_rows,
        "configure_server_capacity": configure_server_capacity,
        "configure_plan_allocation": configure_plan_allocation,
        "configure_tier_allocation": configure_tier_allocation,
        "_select_server_for_plan": _select_server_for_plan,
        "_validate_server_allocation_capacity": _validate_server_allocation_capacity,
        "apply_server_policy": apply_server_policy,
        "plans": plans,
        "get_plan": get_plan,
        "plan_availability": plan_availability,
        "wallet_balance": wallet_balance,
        "wallet_history": wallet_history,
        "consistency_report": consistency_report,
        "credit_wallet": credit_wallet,
        "pay_order_with_wallet": pay_order_with_wallet,
        "list_pending_orders": list_pending_orders,
        "approve_order": approve_order,
        "reject_order": reject_order,
        "refund_order": refund_order,
    }.items()
}

STATIC_SERVICE_IMPLEMENTATIONS = {
    "_assert_no_active_promo",
    "_audit",
    "_health_threshold",
    "_lock_order",
    "_metric_bytes",
    "_queue_customer_repair_notification",
    "_queue_receipt_extraction",
    "_queue_staff_notification",
    "_receipt_storage_extension",
    "_receipt_storage_path",
    "_receipt_timestamp",
    "_repair_blocks_access",
    "_table_exists",
    "_managed_repair_allow_unknown_usage",
    "_managed_repair_cached_usage_max_age_seconds",
    "_managed_repair_key_name",
    "_managed_repair_observation_interval_seconds",
    "_managed_repair_required_observations",
    "_order_stage",
    "_usage_snapshot_interval_seconds",
    "_validate_server_allocation_capacity",
}
