"""Explicit mapping from entitlement API names to focused handlers."""

from __future__ import annotations

from typing import Any

from entitlement_giveaways import (
    _campaign_state,
    _campaign_window_start,
    _commerce_tables_exist,
    _has_active_promo_gift,
    _intent_tables_exist,
    _lock_user,
    claim,
    claim_giveaway,
    claim_trial,
    configure_giveaway,
    giveaway_status,
    reconcile_giveaway_limits,
    set_giveaway_active,
    track_user,
)
from entitlement_provisioning import (
    _adjust_remote_key_count,
    _claim_free_intent,
    _create_key_idempotent,
    _default_server_id,
    _deterministic_slot_id,
    _execute_free_intent,
    _finalize_free_intent,
    _free_intent_done,
    _free_intent_failed,
    _insert_free_intent,
    _intent_result,
    _latest_free_intent,
    _outline_client,
    _remote_key_for_intent,
    _reset_free_intent,
    _select_server_for_tier,
    _server_tables_exist,
    _sync_identity_key,
    _table_exists,
    process_provisioning_intents,
)
from entitlement_quota import (
    _terminate_key,
    _usage_for_server,
    collect_metrics,
    enforce_quota,
    mark_termination_notice,
    pending_termination_notices,
    quota_alert_preferences,
    queue_quota_warnings,
    reconcile_terminations,
    revoke_expired,
    set_quota_alert_preferences,
    termination_summary,
    user_migrated_usage,
    user_usage,
)


ENTITLEMENT_IMPLEMENTATIONS: dict[str, Any] = {
    name: implementation
    for name, implementation in {
        "_campaign_state": _campaign_state,
        "_campaign_window_start": _campaign_window_start,
        "_commerce_tables_exist": _commerce_tables_exist,
        "_has_active_promo_gift": _has_active_promo_gift,
        "_intent_tables_exist": _intent_tables_exist,
        "_lock_user": _lock_user,
        "claim": claim,
        "claim_giveaway": claim_giveaway,
        "claim_trial": claim_trial,
        "configure_giveaway": configure_giveaway,
        "giveaway_status": giveaway_status,
        "reconcile_giveaway_limits": reconcile_giveaway_limits,
        "set_giveaway_active": set_giveaway_active,
        "track_user": track_user,
        "_adjust_remote_key_count": _adjust_remote_key_count,
        "_claim_free_intent": _claim_free_intent,
        "_create_key_idempotent": _create_key_idempotent,
        "_default_server_id": _default_server_id,
        "_deterministic_slot_id": _deterministic_slot_id,
        "_execute_free_intent": _execute_free_intent,
        "_finalize_free_intent": _finalize_free_intent,
        "_free_intent_done": _free_intent_done,
        "_free_intent_failed": _free_intent_failed,
        "_insert_free_intent": _insert_free_intent,
        "_intent_result": _intent_result,
        "_latest_free_intent": _latest_free_intent,
        "_outline_client": _outline_client,
        "_remote_key_for_intent": _remote_key_for_intent,
        "_reset_free_intent": _reset_free_intent,
        "_select_server_for_tier": _select_server_for_tier,
        "_server_tables_exist": _server_tables_exist,
        "_sync_identity_key": _sync_identity_key,
        "_table_exists": _table_exists,
        "process_provisioning_intents": process_provisioning_intents,
        "_terminate_key": _terminate_key,
        "_usage_for_server": _usage_for_server,
        "collect_metrics": collect_metrics,
        "enforce_quota": enforce_quota,
        "mark_termination_notice": mark_termination_notice,
        "pending_termination_notices": pending_termination_notices,
        "quota_alert_preferences": quota_alert_preferences,
        "queue_quota_warnings": queue_quota_warnings,
        "reconcile_terminations": reconcile_terminations,
        "revoke_expired": revoke_expired,
        "set_quota_alert_preferences": set_quota_alert_preferences,
        "termination_summary": termination_summary,
        "user_migrated_usage": user_migrated_usage,
        "user_usage": user_usage,
    }.items()
}

STATIC_ENTITLEMENT_IMPLEMENTATIONS = {
    "_campaign_state",
    "_campaign_window_start",
    "_commerce_tables_exist",
    "_has_active_promo_gift",
    "_intent_tables_exist",
    "_lock_user",
    "_deterministic_slot_id",
    "_server_tables_exist",
    "_table_exists",
    "_usage_for_server",
}
