"""Structural repository contracts used while the modular monolith is extracted."""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class RepositoryDatabase(Protocol):
    """Minimum transaction boundary required by domain services."""

    def connect(self) -> AbstractContextManager[Any]: ...

    def begin_write(self, connection: Any) -> None: ...

    def is_integrity_error(self, error: Exception) -> bool: ...

    def initialize(self) -> None: ...


@runtime_checkable
class HostedRepositoryDatabase(RepositoryDatabase, Protocol):
    """Repository whose external connection resources need process shutdown."""

    def close(self) -> None: ...


@runtime_checkable
class OrderRepositoryPort(Protocol):
    """Transaction-neutral queries required by the commerce order workflow."""

    def get(self, connection: Any, order_id: str) -> Any: ...

    def get_owned(self, connection: Any, order_id: str, telegram_id: int) -> Any: ...

    def find_open_for_user(self, connection: Any, telegram_id: int) -> Any: ...

    def get_payment_context(self, connection: Any, order_id: str) -> Any: ...

    def lock_user(self, connection: Any, telegram_id: int) -> None: ...

    def enabled_server_count(self, connection: Any) -> int: ...

    def insert_wallet_topup(self, connection: Any, **values: Any) -> None: ...

    def insert_order(self, connection: Any, **values: Any) -> None: ...

    def cancel(self, connection: Any, order_id: str, cancelled_at: str) -> None: ...

    def expired_open_orders(self, connection: Any, cutoff: str) -> list[Any]: ...

    def expired_wallet_reservations(self, connection: Any, cutoff: str) -> list[Any]: ...

    def wallet_ledger_exists(self, connection: Any, idempotency_key: str) -> bool: ...

    def credit_wallet(self, connection: Any, **values: Any) -> None: ...

    def insert_wallet_ledger(self, connection: Any, **values: Any) -> None: ...

    def release_wallet_reservation(self, connection: Any, order_id: str, updated_at: str) -> None: ...

    def reject_wallet_payment(self, connection: Any, order_id: str) -> None: ...

    def cancel_submitted_order(self, connection: Any, order_id: str, rejected_at: str) -> None: ...

    def insert_notification(self, connection: Any, **values: Any) -> None: ...

    def open_order_users(self, connection: Any) -> list[Any]: ...

    def open_orders_for_user(self, connection: Any, telegram_id: int) -> list[Any]: ...

    def cancel_duplicate(self, connection: Any, order_id: str) -> None: ...

    def list_user_orders(self, connection: Any, telegram_id: int, limit: int) -> list[Any]: ...

    def detail(self, connection: Any, order_id: str) -> Any: ...

    def update_payment_method(self, connection: Any, order_id: str, method: str) -> None: ...

    def insert_payment(self, connection: Any, **values: Any) -> None: ...

    def mark_payment_submitted(self, connection: Any, order_id: str) -> None: ...

    def mark_wallet_payment_submitted(self, connection: Any, order_id: str) -> None: ...

    def open_order_ids(self, connection: Any, telegram_id: int, limit: int) -> list[Any]: ...


@runtime_checkable
class WalletReadRepositoryPort(Protocol):
    """Wallet reads and consistency-report persistence boundary."""

    def user_exists(self, connection: Any, telegram_id: int) -> bool: ...

    def wallet_currency(self, connection: Any, telegram_id: int) -> Any: ...

    def ensure_wallet(self, connection: Any, **values: Any) -> None: ...

    def balance(self, connection: Any, telegram_id: int) -> Any: ...

    def history(self, connection: Any, telegram_id: int, currency: str, limit: int) -> list[Any]: ...

    def consistency_report(self, connection: Any, review_cutoff: str) -> dict[str, int]: ...

    def pending_orders(self, connection: Any, limit: int) -> list[Any]: ...


@runtime_checkable
class CommerceJobRepositoryPort(Protocol):
    """Provisioning-job lease and retry persistence operations."""

    def claim(self, connection: Any, operation: str, now_text: str, stale_before: str) -> Any: ...

    def mark_done(self, connection: Any, job_id: str) -> None: ...

    def mark_failed(self, connection: Any, **values: Any) -> None: ...

    def failed_jobs(self, connection: Any, limit: int, include_nonterminal: bool) -> list[Any]: ...

    def failed_job(self, connection: Any, job_id: str) -> Any: ...

    def reset(self, connection: Any, job_id: str, now_text: str) -> None: ...

    def failed_job_for_order(self, connection: Any, order_id: str, operation: str | None) -> Any: ...


@runtime_checkable
class PaymentRepositoryPort(Protocol):
    """Payment/evidence reads used by order workflows."""

    def activity_counts(self, connection: Any, order_id: str) -> tuple[int, int]: ...

    def has_evidence(self, connection: Any, order_id: str) -> bool: ...

    def payments_for_order(self, connection: Any, order_id: str) -> list[Any]: ...

    def latest_payment(self, connection: Any, order_id: str) -> Any: ...

    def latest_eligible_payment(self, connection: Any, order_id: str) -> Any: ...

    def verified_payment(self, connection: Any, order_id: str) -> Any: ...

    def verified_evidence(self, connection: Any, order_id: str) -> Any: ...

    def latest_evidence_review(self, connection: Any, order_id: str) -> Any: ...

    def latest_evidence_for_approval(self, connection: Any, order_id: str) -> Any: ...

    def verified_evidence_amount(self, connection: Any, order_id: str) -> Any: ...

    def find_exact_duplicate(
        self,
        connection: Any,
        image_sha256: str,
        file_unique_id: str | None,
        exclude_order_id: str | None = None,
    ) -> list[Any]: ...

    def prior_phash_rows(self, connection: Any, exclude_order_id: str | None = None) -> list[Any]: ...

    def existing_evidence(self, connection: Any, order_id: str, image_sha256: str) -> Any: ...

    def transaction_candidates(
        self,
        connection: Any,
        exclude_order_id: str,
        exclude_evidence_id: str | None = None,
    ) -> list[Any]: ...

    def list_pending_receipts(self, connection: Any, limit: int) -> list[Any]: ...

    def get_receipt(self, connection: Any, evidence_id: str) -> Any: ...

    def verification_context(self, connection: Any, evidence_id: str) -> Any: ...

    def payment_reference_conflicts(self, connection: Any, normalized_reference: str, order_id: str) -> list[Any]: ...

    def insert_verified_payment(self, connection: Any, **values: Any) -> None: ...

    def update_verified_payment(self, connection: Any, **values: Any) -> None: ...

    def mark_evidence_verified(self, connection: Any, **values: Any) -> None: ...


@runtime_checkable
class WalletApprovalRepositoryPort(Protocol):
    """Persistence commands used inside one order-approval transaction."""

    def subscription_id_for_order(self, connection: Any, order_id: str) -> str | None: ...

    def ledger_entry_exists(self, connection: Any, idempotency_key: str) -> bool: ...

    def wallet_reservation(self, connection: Any, order_id: str) -> Any: ...

    def plan(self, connection: Any, plan_code: str) -> Any: ...

    def ensure_wallet(
        self, connection: Any, *, telegram_id: int, currency: str, now_text: str
    ) -> None: ...

    def credit_once(
        self,
        connection: Any,
        *,
        entry_id: str,
        telegram_id: int,
        amount_minor: int,
        currency: str,
        reference_type: str,
        reference_id: str,
        idempotency_key: str,
        now_text: str,
    ) -> bool: ...

    def reserve_once(
        self,
        connection: Any,
        *,
        ledger_entry_id: str,
        reservation_id: str,
        telegram_id: int,
        order_id: str,
        amount_minor: int,
        currency: str,
        idempotency_key: str,
        now_text: str,
    ) -> bool: ...

    def capture_once(
        self,
        connection: Any,
        *,
        ledger_entry_id: str,
        reservation_id: str,
        telegram_id: int,
        order_id: str,
        amount_minor: int,
        currency: str,
        idempotency_key: str,
        now_text: str,
    ) -> None: ...

    def mark_order_approved(
        self, connection: Any, order_id: str, approved_at: str
    ) -> None: ...

    def mark_payment_verified(
        self, connection: Any, payment_id: str, verified_at: str
    ) -> None: ...

    def create_subscription(
        self,
        connection: Any,
        *,
        subscription_id: str,
        order_id: str,
        telegram_id: int,
        plan_code: str,
        starts_at: str,
        expires_at: str,
        plan_name: str,
        quota_bytes: int | None,
        duration_days: int,
        server_id: str | None,
    ) -> None: ...

    def queue_provisioning(
        self,
        connection: Any,
        *,
        job_id: str,
        subscription_id: str,
        next_attempt_at: str,
        created_at: str,
    ) -> None: ...

    def queue_notification(
        self,
        connection: Any,
        *,
        notification_id: str,
        dedupe_key: str,
        telegram_id: int,
        kind: str,
        text: str,
        now_text: str,
    ) -> None: ...

    def reject_order(self, connection: Any, **values: Any) -> None: ...

    def refund_order(self, connection: Any, **values: Any) -> None: ...


@runtime_checkable
class IdentityUsageRepositoryPort(Protocol):
    """Persistence operations used inside one remote-usage transaction."""

    def active_binding(self, connection: Any, endpoint_id: str, external_id: str) -> Any: ...

    def active_epoch(self, connection: Any, **criteria: Any) -> Any: ...

    def latest_epoch_no(self, connection: Any, **criteria: Any) -> int: ...

    def create_epoch(self, connection: Any, **values: Any) -> None: ...

    def mark_epoch_reset(self, connection: Any, epoch_id: str, now_text: str) -> None: ...

    def update_epoch_remote(self, connection: Any, **values: Any) -> None: ...

    def duplicate_sample(self, connection: Any, **criteria: Any) -> Any: ...

    def record_sample(self, connection: Any, **values: Any) -> None: ...

    def active_leases(self, connection: Any, **criteria: Any) -> list[dict[str, Any]]: ...

    def create_lease(self, connection: Any, **values: Any) -> None: ...

    def consume_lease(self, connection: Any, **values: Any) -> None: ...

    def credit_epoch(self, connection: Any, **values: Any) -> None: ...

    def set_entitlement_consumed(self, connection: Any, **values: Any) -> None: ...


@runtime_checkable
class InventoryReconciliationRepositoryPort(Protocol):
    """Persistence operations used during remote inventory reconciliation."""

    def enabled_server_ids(self, connection: Any) -> list[str]: ...

    def remote_key_ledger(
        self, connection: Any, server_id: str
    ) -> dict[str, dict[str, Any]]: ...

    def managed_key_ids(
        self, connection: Any, server_id: str, *, include_free_keys: bool
    ) -> set[str]: ...

    def mark_present_keys_missing(self, connection: Any, server_id: str) -> None: ...

    def upsert_present_key(self, connection: Any, **values: Any) -> None: ...

    def update_managed_usage(self, connection: Any, **values: Any) -> None: ...

    def upsert_missing_key(self, connection: Any, **values: Any) -> None: ...

    def unreviewed_orphan_count(self, connection: Any, server_id: str) -> int: ...

    def update_server_metrics(self, connection: Any, **values: Any) -> None: ...

    def lifecycle_state(self, connection: Any, server_id: str) -> str: ...


@runtime_checkable
class CapacitySnapshotRepositoryPort(Protocol):
    """Persistence read model for capacity and admission snapshots."""

    def snapshot_inputs(self, connection: Any, **criteria: Any) -> dict[str, Any]: ...

    def server_commitments(self, connection: Any, **criteria: Any) -> dict[str, int]: ...


@runtime_checkable
class ProvisioningRepositoryPort(Protocol):
    """Persistence operations for one paid provisioning job."""

    def context(self, connection: Any, subscription_id: str) -> tuple[Any, Any]: ...

    def defer_job(self, connection: Any, job_id: str, next_attempt_at: str) -> None: ...

    def expire_subscription(
        self, connection: Any, subscription_id: str, expected_status: str
    ) -> None: ...

    def mark_job_expired(self, connection: Any, job_id: str) -> None: ...

    def insert_key(self, connection: Any, **values: Any) -> None: ...

    def activate_subscription(self, connection: Any, **values: Any) -> None: ...

    def queue_ready_notification(self, connection: Any, **values: Any) -> None: ...

    def mark_job_done(self, connection: Any, job_id: str) -> None: ...


@runtime_checkable
class FleetHealthRepositoryPort(Protocol):
    """Persistence operations for endpoint lifecycle and health transitions."""

    def server(self, connection: Any, server_id: str) -> Any: ...

    def retirement_counts(self, connection: Any, server_id: str, **flags: Any) -> dict[str, int]: ...

    def set_lifecycle(self, connection: Any, **values: Any) -> None: ...

    def health_state_for_update(self, connection: Any, server_id: str) -> Any: ...

    def duplicate_observation(
        self, connection: Any, server_id: str, observed_at: str
    ) -> Any: ...

    def update_health(self, connection: Any, **values: Any) -> None: ...

    def record_observation(self, connection: Any, **values: Any) -> None: ...


@runtime_checkable
class EntitlementAllocationRepositoryPort(Protocol):
    """Capacity evidence used to choose an entitlement endpoint."""

    def fleet_size(self, connection: Any) -> int: ...

    def eligible_servers(self, connection: Any, fresh_after: str) -> list[Any]: ...

    def has_tier_allocations(self, connection: Any, tier_code: str) -> bool: ...

    def route_health(self, connection: Any, server_id: str) -> Any: ...

    def tier_allocation(self, connection: Any, server_id: str, tier_code: str) -> Any: ...

    def active_tier_count(self, connection: Any, server_id: str, tier_code: str) -> int: ...

    def pending_tier_count(self, connection: Any, server_id: str, kind: str) -> int: ...

    def traffic_commitment(self, connection: Any, server_id: str) -> tuple[int, int]: ...

    def record_decision(self, connection: Any, **values: Any) -> None: ...


@runtime_checkable
class ReceiptSubmissionRepositoryPort(Protocol):
    """Persistence operations for the receipt upload state machine."""

    def mark_order_submitted(self, connection: Any, order_id: str) -> None: ...

    def mark_upload_pending(self, connection: Any, **values: Any) -> None: ...

    def insert_evidence(self, connection: Any, **values: Any) -> None: ...

    def mark_upload_failed(
        self, connection: Any, evidence_id: str, error_type: str
    ) -> None: ...

    def mark_stored(self, connection: Any, **values: Any) -> None: ...


@runtime_checkable
class EntitlementProvisioningRepositoryPort(Protocol):
    """Persistence operations for durable free/trial/promo provisioning."""

    def table_exists(self, connection: Any, name: str) -> bool: ...

    def server_tables_exist(self, connection: Any) -> bool: ...

    def adjust_remote_key_count(self, connection: Any, server_id: str, delta: int) -> None: ...

    def active_credential(self, connection: Any, server_id: str, external_id: str) -> Any: ...

    def claim_intent(self, connection: Any, **values: Any) -> dict[str, Any] | None: ...

    def reset_intent(self, connection: Any, intent_id: str, next_attempt_at: str) -> None: ...

    def mark_failed(self, connection: Any, **values: Any) -> None: ...

    def mark_done(self, connection: Any, **values: Any) -> None: ...

    def existing_key(self, connection: Any, server_id: str, outline_key_id: str) -> Any: ...

    def insert_key(self, connection: Any, **values: Any) -> int: ...

    def update_user_claim(self, connection: Any, **values: Any) -> None: ...

    def giveaway_claim(self, connection: Any, campaign_code: str, telegram_id: int) -> Any: ...

    def insert_giveaway_claim(self, connection: Any, **values: Any) -> None: ...

    def giveaway_window(self, connection: Any, campaign_code: str, window_start: str) -> Any: ...

    def insert_giveaway_window(self, connection: Any, campaign_code: str, window_start: str) -> None: ...

    def increment_giveaway_window(self, connection: Any, campaign_code: str, window_start: str) -> None: ...

    def increment_campaign(self, connection: Any, campaign_code: str, now_text: str) -> None: ...

    def intent_by_id(self, connection: Any, intent_id: str) -> Any: ...

    def update_intent_outline_key(self, connection: Any, intent_id: str, outline_key_id: str) -> None: ...

    def insert_intent(self, connection: Any, **values: Any) -> dict[str, Any]: ...

    def latest_intent(
        self, connection: Any, telegram_id: int, kind: str, campaign_code: str | None
    ) -> dict[str, Any] | None: ...

    def campaign_counts(self, connection: Any, campaign_code: str) -> Any: ...


@runtime_checkable
class CommerceAllocationRepositoryPort(Protocol):
    """Persistence operations for server and plan allocation policy."""

    def update_server_capacity(self, connection: Any, **values: Any) -> Any: ...

    def enabled_server(self, connection: Any, server_id: str) -> Any: ...

    def plan(self, connection: Any, plan_code: str, **flags: Any) -> Any: ...

    def upsert_plan_allocation(self, connection: Any, **values: Any) -> None: ...

    def upsert_tier_allocation(self, connection: Any, **values: Any) -> None: ...

    def allocation_capacity(self, connection: Any, server_id: str) -> tuple[Any, int, int]: ...

    def policy_state(self, connection: Any, server_id: str) -> tuple[Any, dict[str, int], dict[str, int]]: ...

    def clear_policy(self, connection: Any, server_id: str, now_text: str) -> None: ...

    def write_policy_values(self, connection: Any, **values: Any) -> None: ...

    def selection_inputs(self, connection: Any, **values: Any) -> dict[str, Any]: ...

    def record_decision(self, connection: Any, **values: Any) -> None: ...

    def active_plans(self, connection: Any) -> list[Any]: ...

    def active_plan(self, connection: Any, code: str) -> Any: ...

    def availability_inputs(self, connection: Any, fresh_after: str, now_text: str) -> dict[str, Any]: ...

    def used_for_plan(self, connection: Any, server_id: str, plan_code: str, now_text: str) -> int: ...


@runtime_checkable
class IdentityGenerationsRepositoryPort(Protocol):
    """Persistence operations for credential generations and quota leases."""

    def ensure_generation_for_credential(self, connection: Any, **values: Any) -> str: ...

    def active_lease_for_generation(self, connection: Any, generation_id: str) -> str | None: ...

    def create_generation(self, connection: Any, **values: Any) -> str: ...

    def revoke_generation(self, connection: Any, generation_id: str, timestamp: str) -> bool: ...

    def grant_lease(self, connection: Any, **values: Any) -> str: ...

    def mark_entitlement_exhausted(self, connection: Any, entitlement_id: str, **values: Any) -> bool: ...

    def release_lease(self, connection: Any, lease_id: str, **values: Any) -> bool: ...
